### ISSUE TITLE
[QUESTION] icloud backup after all steps

### ISSUE THREAD

**Issue by Riggola** [iammanpreetsingh/WhatsApp-Watusi-Restore#1]
Hello man, im glad to see the fisrt method to restore whatsapp data to watusi, but the only thing that stop me is one, after all steps it is possible to enable the icloud backup again or just having the modified ipa will block the backup anyway? im really scared to lost chats or having to backup it everytime manually, or aleast a way for reimport it to the stock whatsapp app.... 
thank you

**Comment by iammanpreetsingh** [comment]
The iCloud Backup can be enabled once you reinstall WhatsApp and set up some things. Those "some things", I am working on that. And I will update the method soon.

**Comment by Riggola** [comment]
With reinstall WhatsApp you mean the stock one right? If yes, you have lost the backup already for restoring chat to watusi version so you are working on a method to port backup from watusi to iCloud before back to the stock one or you will lost the chat forever? I miss that part 😅

**Comment by iammanpreetsingh** [comment]
> 

No, You will not lose any chats whatsoever. 

I have different methods to retain the data forever. Allow me some time and I'll update the methods here.

**Comment by Riggola** [comment]
I will wait then, Ty
