### ISSUE TITLE
Can't install on PlayCover running on M1 mac | Code object is not signed at all

### ISSUE THREAD

**Issue by FreedomLabsIO** [iammanpreetsingh/WhatsApp-Watusi-Restore#11]
When I try to install the IPA file on my M1 mac using PlayCover I get this error, any ideas how to fix this?

![image](https://github.com/iammanpreetsingh/WhatsApp-Watusi-Restore/assets/5354345/d49d8ab6-7401-4b8e-9c54-669d94182feb)

**Comment by iammanpreetsingh** [comment]
WhatsApp needs to be built with ARM architecture to be able to install on M1 Macs. Just use WhatsApp for Mac.
