### ISSUE TITLE
OnlineNotify not loaded properly

### ISSUE THREAD

**Issue by dineshanantharaja** [iammanpreetsingh/WhatsApp-Watusi-Restore#12]
I just sideloaded this app and it works great.
After enabling OnlineNotify tweak, applying it and restarting the app, I get a pop up saying “OnlineNotify not loaded properly”. Is there a way to fix this.

**Comment by iammanpreetsingh** [comment]
Which version are you using?

**Comment by dineshanantharaja** [comment]
I’m using the latest release on GitHub. 

WhatsApp 23.18.75_Watusi_1.2.1_Stalky_4.1.23_OnlineNotify_3.4.3

**Comment by iammanpreetsingh** [comment]
Fixed.

**Comment by dineshanantharaja** [comment]
Hi I am still getting this issue
