### ISSUE TITLE
Can’t connect Watusi as a Multi-Device

### ISSUE THREAD

**Issue by beyto1010** [iammanpreetsingh/WhatsApp-Watusi-Restore#15]
When I attempt to scan the QR code, I receive an error message stating ‘that’s currently not possible.’ Upon checking Watusi, it appears that the QR code expires as soon as I put the app in the background. Is there a workaround for this issue?

**Comment by iammanpreetsingh** [comment]
My apologies for the delayed response. You should inject the WhatsApp freeze dylib from the apptesters repository.
