### ISSUE TITLE
The message doesn’t sync from the server

### ISSUE THREAD

**Issue by youssiefadel** [iammanpreetsingh/WhatsApp-Watusi-Restore#17]
The message doesn’t sync from the server

**Comment by iammanpreetsingh** [comment]
Hi, do you mean iCloud?

**Comment by youssiefadel** [comment]
Hey,
Thank you for response. Kindly , find the below photo 
![IMG_6859](https://github.com/user-attachments/assets/fef33b3d-7fd7-458d-bd07-bf632e2c67d4)
