### ISSUE TITLE
can't sign the latest version

### ISSUE THREAD

**Issue by OmriKu** [iammanpreetsingh/WhatsApp-Watusi-Restore#3]
error message while trying to sign:
Error verifying code signature!
/var/folders/ym/7dbmq_rn0mvgmg9469tggjwm0000gn/T/com.DanTheMan827.AppSigner.gy2aU9Vh/out/Payload/WhatsApp.app: invalid signature (code or signature have been modified)
In architecture: arm64

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'working directory doesn't exist.'
terminating with uncaught exception of type NSException
abort() called

**Comment by iammanpreetsingh** [comment]
Thanks for letting me know. I have found the issue. I will update the IPA.

**Comment by iammanpreetsingh** [comment]
Fixed.
