### ISSUE TITLE
How to revert back to original whatsapp

### ISSUE THREAD

**Issue by ghost** [iammanpreetsingh/WhatsApp-Watusi-Restore#8]
So i started using whatsapp watsui a few months ago, and now i want to revert to original whatsapp with my messages and data since its hassle refreshing app via altstore every week

**Comment by iammanpreetsingh** [comment]
You should get a lifetime certificate from
www.apptesters.org/purchase-certificate to avoid resigning. 

if you want to switch back you need a jailbroken device or trollstore device.
