### ISSUE TITLE
Whatsapp Update

### ISSUE THREAD

**Issue by Trible789** [iammanpreetsingh/WhatsApp-Watusi-Restore#9]
Current Version of WhatsApp-Watusi-Restore is 23.12.71. This Version is about to expire in a few days. Please Update the IPA to a newer Whatsapp Version

**Comment by Venerex80** [comment]
Hi ,I displayed this message when I tried to open Watusi on AltStore after updating to iOS to 16.5.1 : “ this version of WhatsApp is expired. Update WhatsApp “ tried to refresh the app with AltStore but message still there. Any idea of how can I fix it or sideload a new ipa without deleting the app ? Thanks

**Comment by iammanpreetsingh** [comment]
Updated!
